version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: stock-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/backend/models
    environment:
      - PYTHONUNBUFFERED=1
      - OFFLINE_MODE=1
      - BOOTSTRAP_TICKERS=MSFT,AAPL
      - BOOTSTRAP_HORIZONS=5
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: stock-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
